### PR TITLE
added regular and extralight otf files

### PR DESCRIPTION
**Pull request by CntrlX**

### CODE REVIEW

**Comment by OmarMcAdam** [comment]
can you please upload the otf so I can test this
just having the glyph files is useless for me

**Comment by CntrlX** [comment]
Come on bro that's what i did first then some dude said you need the glyph file

**Comment by CntrlX** [comment]
The otf files are in the older commit

**Comment by OmarMcAdam** [comment]
who said the glyph?
lemme look at that

**Comment by OmarMcAdam** [comment]
i see https://github.com/calcom/font/issues/2#issuecomment-1759961818
lemme test with the otfs

**Comment by OmarMcAdam** [comment]
i dunno what this is, but it aint cal sans 😂
the extra light is all messed up
image

regular also does not look like cal sans
image

THIS is cal sans
image

**Pull request closed without merging**
