### PR TITLE
feat: setup npm package

### PR DESCRIPTION
**Pull request by grikomsn**
Related to https://twitter.com/calendso/status/1466822875231531014, this PR sets up npm package named `cal-sans`\. At the time of writing this, package name has not been taken.

Sources are based from [grikomsn/cal-sans, a repository which does the same thing](https://github.com/grikomsn/cal-sans) but uses this repository as a dependency to import the font files. If `cal-sans` is published, previous package will be deprecated.

This PR also updates the readme structure and contents to emphasize on how to install via npm or yarn.

## Checklist

- [ ] Upload initial package to claim npm package name
- [ ] Test font usage
- [ ] Include live examples on readme

### CODE REVIEW

**Comment by grikomsn** [comment]
Thank you for merging! Apparently the package hasn’t been published. Any estimate on when it’ll be published?

**Comment by PeerRich** [comment]
will do tomorrow! had some minor issues with npm initially and now i have to wait 24 hours before resubmitting

**Comment by grikomsn** [comment]
Let me know if there's anything I can help on publishing the package. 👋🏻

**Comment by PeerRich** [comment]
done https://www.npmjs.com/package/cal-sans

**Pull request merged**
